// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Collection: typeof import('./src/components/Collection.vue')['default']
    CreateNode: typeof import('./src/components/CreateNode.vue')['default']
    CurrentNode: typeof import('./src/components/CurrentNode.vue')['default']
    Garbage: typeof import('./src/components/Garbage.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Node: typeof import('./src/components/Node.vue')['default']
    NodeBooks: typeof import('./src/components/NodeBooks.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    ShowNode: typeof import('./src/components/ShowNode.vue')['default']
    SignIn: typeof import('./src/components/SignIn.vue')['default']
    Tool: typeof import('./src/components/Tool.vue')['default']
    Translate: typeof import('./src/components/Translate.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}

export { }
